from typing import Protocol, Optional

from wx_ai_assistant.domain.models import ConversationIdentity, ListenTarget, Message, SendTask
from wx_ai_assistant.domain.enums import ListenStatus, SendTaskStatus


class Repository(Protocol):
    def initialize_schema(self) -> None: ...
    def upsert_conversation(self, identity: ConversationIdentity) -> None: ...
    def get_conversation(self, conversation_id: str) -> Optional[ConversationIdentity]: ...
    def list_conversations(self) -> list[ConversationIdentity]: ...

    def upsert_listen_target(self, target: ListenTarget) -> None: ...
    def set_listen_status(self, conversation_id: str, status: ListenStatus, last_error: str | None = None) -> None: ...
    def list_listen_targets(self) -> list[ListenTarget]: ...
    def get_listen_target(self, conversation_id: str) -> Optional[ListenTarget]: ...

    def insert_message_if_new(self, message: Message) -> bool: ...
    def list_recent_messages(self, conversation_id: str, limit: int = 50) -> list[Message]: ...

    def create_send_task(self, task: SendTask) -> None: ...
    def update_send_task(self, task_id: str, status: SendTaskStatus, error_message: str | None = None) -> None: ...
    def list_pending_send_tasks(self, limit: int = 20) -> list[SendTask]: ...
    def list_send_tasks(self, conversation_id: str | None = None, status: SendTaskStatus | None = None, limit: int = 50) -> list[SendTask]: ...
    def get_send_task(self, send_task_id: str) -> Optional[SendTask]: ...
